name: Build with Linux

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      projectPath:
        required: true
        type: string
    secrets:
      UNITY_EMAIL:
        required: true
      UNITY_PASSWORD:
        required: true
      UNITY_LICENSE:
        required: true
    outputs:
      buildVersion:
        value: ${{ jobs.buildWithLinux.outputs.buildVersion }}

jobs:
  buildWithLinux:
    name: Build in Linux for ${{ inputs.platform }}
    runs-on: ubuntu-latest
    outputs:
      buildVersion: ${{ steps.build.outputs.buildVersion }}
    steps:
      # Checkout
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: ${{ inputs.projectPath }}/Library
          key: Library-build-${{ inputs.platform }}
          restore-keys: |
            Library-build-${{ inputs.platform }}
            Library-

      - name: Build Unity Project
        id: build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ${{ inputs.projectPath }}
          targetPlatform: ${{ inputs.platform }}

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ inputs.platform }}
          path: build/${{ inputs.platform }}
