name: Unity WebGL Automatic Build
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  buildForWebGL:
    name: Build for WebGL
    uses: ./.github/workflows/buildWithLinux.yaml
    with:
      platform: WebGL
      projectPath: ./XMAS2024
    secrets:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

  deployToGitHubPages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: buildForWebGL
    steps:
      - name: Echo Build Version
        run: echo ${{ needs.buildForWebGL.outputs.buildVersion }}

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          lfs: false

      - name: Download WebGL Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-WebGL
          path: build/WebGL

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/WebGL/WebGL
          commit-message: Deploy
          single-commit: true

      - name: Cleanup to avoid storage limit
        uses: geekyeggo/delete-artifact@v5
        if: always()
        with:
          name: build-WebGL
          failOnError: false
